name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: npm install and build
      run: |
        npm ci
        npm run build
      env:
        CI: true
